# Generated by Django 2.2.13 on 2020-09-16 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bbs', '0003_remove_review_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='rating',
            field=models.CharField(choices=[('★★★★★', '★★★★★'), ('★★★★☆', '★★★★☆'), ('★★★☆☆', '★★★☆☆'), ('★★☆☆☆', '★★☆☆☆'), ('★☆☆☆☆', '★☆☆☆☆')], default=0, max_length=10),
        ),
    ]
